### ISSUE TITLE
Stardew: Upgrade/Downgrade Item

### ISSUE THREAD

**Issue by MrS4turn** [WarpWorld/CCPack-PC-StardewValley#5]
Since the 1.6 patch, users have reported 2 issues so far.

1. If you try to upgrade/downgrade while fishing, the game seems to softlock 
2. If you try to downgrade anytime, it acts very strange and puts the item in a state that it can no longer be upgrade. It seems to reset it to a base item that gets stuck. Also reports that the game may freeze during a few attempts of this.

**Comment by MrS4turn** [comment]
Additional reports on upgrade, if you are using the thing in anyway while the effect triggers, bad things happen. https://discord.com/channels/168430302954258433/1224110168816750663

**Comment by MrS4turn** [comment]
upgrade/downgrade has been disabled while we review

**Comment by jaku** [comment]
https://github.com/WarpWorld/CCPack-PC-StardewValley/commit/107b60bb0d7a81a0aa54e33d1ea4cdfc9ace8ecc

fixed both reported issues
